### ISSUE TITLE
NullReferenceException while changing column format

### ISSUE THREAD

**Issue by stemaa14** [habjoc/logwizard#18]
A NullReferenceException was thrown after changing the colum format for a log file containing lines like  
`2018-08-07 10:19:27.5844 Info Backend started`.  
Format Syntax: `$date['',' '] $time['',' '] $level['',' '] $msg`  
File: lwcommon/ui/format/column_formatter_array.cs around line 122
```
private bool needs_apply_formatter(formatter format, column_formatter_base.format_cell cell) {
    if (format.column_type == "all")
        return true;
            
    var aliases = cell.parent.filter.log.aliases;
    var cell_type = aliases.to_info_type(format.column_type);
    if (cell_type != info_type.max)
        return cell.col_type == cell_type;

    // in this case, we don't know what column the formater is to be applied to
    return false;
}
```
In the `var aliases...` line `cell.parent.filter.log` is null.

**Comment by habjoc** [comment]
Cannot reproduce.
